package smurf.view;

/**
 * ConfigPanel draws the UI used to allow the user to modify the application configuration settings 
 * 
 * @author Bishan Kumar Madhoo <bishan.madhoo@idsoft.mu>
 * @version 1.0
 */
public class ConfigPanel extends javax.swing.JPanel {

    /**
     * Creates new form RubisPanel
     */
    public ConfigPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        configScrollPane = new javax.swing.JScrollPane();
        configsContainerPanel = new javax.swing.JPanel();
        buttonContainerPanel = new javax.swing.JPanel();
        advancedConfigurationsButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        centerButtonContainerPanel = new javax.swing.JPanel();
        deleteGeneratedFilesButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        titlePanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("Paramétrage de l'application");
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 15, 0));
        titlePanel.add(titleLabel, java.awt.BorderLayout.CENTER);

        add(titlePanel, java.awt.BorderLayout.NORTH);

        configScrollPane.setBackground(new java.awt.Color(238, 238, 238));
        configScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        configScrollPane.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        configsContainerPanel.setLayout(new javax.swing.BoxLayout(configsContainerPanel, javax.swing.BoxLayout.Y_AXIS));
        configScrollPane.setViewportView(configsContainerPanel);

        add(configScrollPane, java.awt.BorderLayout.CENTER);

        buttonContainerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        buttonContainerPanel.setMaximumSize(new java.awt.Dimension(32767, 40));
        buttonContainerPanel.setMinimumSize(new java.awt.Dimension(10, 40));
        buttonContainerPanel.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonContainerPanel.setRequestFocusEnabled(false);
        buttonContainerPanel.setLayout(new java.awt.BorderLayout());

        advancedConfigurationsButton.setText("Paramétrage avancé");
        advancedConfigurationsButton.setActionCommand("ADVANCED_CONFIG");
        buttonContainerPanel.add(advancedConfigurationsButton, java.awt.BorderLayout.WEST);

        saveButton.setText("Enregistrer");
        saveButton.setActionCommand("SAVE_CONFIG");
        buttonContainerPanel.add(saveButton, java.awt.BorderLayout.EAST);

        centerButtonContainerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        centerButtonContainerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        deleteGeneratedFilesButton.setText("Nettoyer les fichiers générés");
        deleteGeneratedFilesButton.setActionCommand("DELETE_GENERATED_FILES");
        centerButtonContainerPanel.add(deleteGeneratedFilesButton);

        buttonContainerPanel.add(centerButtonContainerPanel, java.awt.BorderLayout.CENTER);

        add(buttonContainerPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton advancedConfigurationsButton;
    private javax.swing.JPanel buttonContainerPanel;
    private javax.swing.JPanel centerButtonContainerPanel;
    public javax.swing.JScrollPane configScrollPane;
    public javax.swing.JPanel configsContainerPanel;
    public javax.swing.JButton deleteGeneratedFilesButton;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
