package smurf.view;

/**
 * The SmurfMainJFrame class defines the main application window UI
 * 
 * @author Bishan Kumar Madhoo <bishan.madhoo@idsoft.mu>
 * @version 1.0
 */
public class SmurfMainJFrame extends javax.swing.JFrame {

    /**
     * SmurfMainJFrame default constructor
     */
    public SmurfMainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMURF");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("RubisMainJFrame");

        panelsContainer.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelsContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel panelsContainer;
    // End of variables declaration//GEN-END:variables
}
